Development:
  ###
  # This parameter is used to activate or deactivate the debug mode.
  DEBUG_FLAG: 0             # 1 ... activate 0 ... deactivate
  ###
  # This parameter is used to specify a SBD results file for debugging mode.
  SBD_RESULTS_PATH: "/data/share/maxrecall_vhh_mmsi/release/videos/results/sbd/final_results/2.csv"
  ###
  # This parameter is used to specify the results path in debug mode
  PATH_DEBUG_RESULTS: "/data/share/maxrecall_vhh_mmsi/develop/videos/results/cmc/develop/"
  ###
  # This parameter is used to save a debug package (e.g. including some visualizations, ... - not available yet).
  SAVE_DEBUG_PKG: 0

PreProcessing:
  ###
  # This flag is used to convert a input frame into a grayscale frame (0... deactivate, 1 ... activate).
  CONVERT2GRAY_FLAG: 0
  ###
  # This flag is used to center crop a input frame (0... deactivate, 1 ... activate).
  CENTER_CROP_FLAG: 1       # crop image (origin: image center) with maximum width or height
  ###
  # This flag is used to scale a input frame into the specified dimension (0... deactivate, 1 ... activate).
  DOWNSCALE_FLAG: 1
  ###
  # This flag is used to to specify the resize dimension. (only usable if DOWNSCALE_FLAG is active).
  RESIZE_DIM: 512, 512      # resize dimension -> height, width

OpticalFlow:
  ###
  # This parameter is used to specify a magnitude threshold to disinguish between no-movement and movement. (e.g. eval dataset: 2, 3, 5)
  MIN_MAGNITUDE_THRESHOLD: 1.0
  ###
  # This parameter is used to specify a distance threshold for outlier detection of feature matches
  DISTANCE_THRESHOLD: 0.75
  ###
  # This parameter is used to specify the number of consecutive frames which are needed to register a camera movement.
  SENSITIVITY: 10
  ###
  # This parameter is used to specify the number of outliers (miss detections).
  SPECIFICITY: 3
  ###
  # This parameter is used to specify the frame border inside which random features are created
  BORDER: 10
  ###
  # This parameter is used to specify the number of features number of features to be tracked for optical flow
  NUMBER_OF_FEATURES: 100
  ###
  # This parameter is used to specify the difference limit to most common angle such that still considered as background movement
  ANGLE_DIFF_LIMIT: 10

  ### This parameter is used to select a special mode for optical flow debugging.
  # NORMAL_MODE = 0
  # DEBUG_MODE = 1
  # SAVE_MODE = 2
  # DEBUG_AND_SAVE_MODE = 3
  MODE: 0

CmcCore:
  ###
  # This parameter is used to specify the class names.
  CLASS_NAMES: ["pan","tilt","na"]

  ###
  # This parameter is used to save raw results (e.g. debug visualizations).
  SAVE_RAW_RESULTS: 0       # 1 ... yes 0 ... no
  ###
  # This parameter is used to specify the path for saving the raw results.
  PATH_RAW_RESULTS: "/data/share/jocch_paper_cmc_results/raw_results/"
  NUMBER_OF_FRAMES_PER_SHOT: 5  # save x frames per shot
  ###
  # This parameter is used to specify the prefix for the results file.
  PREFIX_RAW_RESULTS: "results_raw_"
  ###
  # This parameter is used to specify the postfix for the results file.
  POSTFIX_RAW_RESULTS: "csv"

  ###
  # This parameter is used to save final results (e.g. csv list).
  SAVE_FINAL_RESULTS: 1     # 1 ... yes 0 ... no
  ###
  # This parameter is used to specify the path for saving the final results.
  PATH_FINAL_RESULTS: "/data/share/jocch_paper_cmc_results/final_results/"
  ###
  # This parameter is used to specify the prefix for the results file.
  PREFIX_FINAL_RESULTS: "results_"
  ###
  # This parameter is used to specify the postfix for the results file.
  POSTFIX_FINAL_RESULTS: "csv"

  ###
  # This parameter is used to specify the path to the videos.
  PATH_VIDEOS: "/data/share/maxrecall_vhh_mmsi/develop/videos/downloaded/"  #   /data/share/maxrecall_vhh_mmsi/develop/videos/downloaded/ /data/share/datasets/cmc_final_dataset_v2/

Evaluation:
  ###
  # This parameter is used to save evaluation results (e.g. visualizations, ... ).
  SAVE_EVAL_RESULTS: 1
  ###
  # This parameter is used the raw results path.
  PATH_RAW_RESULTS: "/data/share/maxrecall_vhh_mmsi/develop/videos/results/cmc/raw_results/"
  ###
  # This parameter is used to specify the path to store the evaluation results path.
  PATH_EVAL_RESULTS: "/data/share/jocch_paper_cmc_results/vhh_mmsi_test_db_v2_final_results_mag_th_1/"
  ###
  # This parameter is used to groundtruth annotations used for evaluation.
  PATH_GT_ANNOTATIONS: "/caa/Projects02/vhh/private/database_nobackup/VHH_datasets/annotations/ShotBoundaryDetection/imediacities/sbd_imc_annotations_20191231.csv"
  ###
  # This parameter is used to specify the path to the dataset used for the evaluation.
  PATH_EVAL_DATASET: "/data/share/datasets/vhh_mmsi_test_db_v2/"   # vhh_mmsi_test_db_v2   cmc_final_dataset_v2
