# ----------- DEFAULTS FOR THE OPTICAL FLOW CLASSIFIER ----------- #
# consecutive frames
SENSITIVITY: 20
# outliers, range in which for mca is looked
SPECIFICITY: 3
# of frame inside which random features are created
BORDER: 50
# number of features to be tracked for optical flow
NUMBER_OF_FEATURES: 100
# difference to most common angle such that still considered as background movement
ANGLE_DIFF_LIMIT: 20
# the run mode for the classifier
# NORMAL_MODE = 0
# DEBUG_MODE = 1
# SAVE_MODE = 2
# DEBUG_AND_SAVE_MODE = 3
MODE: 0

# ----------- DEFAULTS FOR THE VIDEO WHICH IS TO BE CLASSIFIED ----------- #
# name of the video with .mp4 suffix
INPUT_VIDEO: "EF-NS_001_OeFM.mp4"
# name of the annotated video with .avi suffix. if empty the input name will be used with suffix _ann.
OUTPUT_VIDEO: ""
# name of the plot with .png suffix showing all most common angles and the classified movements. if empty the input name will be used with suffix _movements.
OUTPUT_PLOT: ""
# name of the csv where all start / end frame indexes and movement classification PAN / TILT will be listed.
OUTPUT_CSV: "result.csv"
# the path of the input folder. must be located in sub folder of working directory.
INPUT_PATH: "/input"
# the path of the output folder. must be located in sub folder of working directory.
OUTPUT_PATH: "/output"
# the start frame for the classification.
BEGIN_FRAME: 0
# the last frame to be classified. if 1 the entire video will be classified.
END_FRAME: 1